In [1]:
pip install numpy #PREFERRED INSTALLER PROGRAM

In [4]:
import numpy as np


In [23]:
np1 = np.array([1,2,3,4,5,6])
print(np1)
type(np1)


[1 2 3 4 5 6]


numpy.ndarray

In [4]:
np1=np.array([[1,2,3],[2,3,4],[3,5,6]])
print(np1)

[[1 2 3]
 [2 3 4]
 [3 5 6]]


In [6]:
np1=np.array([[1,2,3],[3,4,5]])
print(np1)

[[1 2 3]
 [3 4 5]]


In [7]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(3, 19, 3)
type(np.arange)

builtin_function_or_method

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [21]:
np.empty(3)

array([1., 1., 1.])

In [24]:
np1=np.array([8,3,4,9,6])
np.sort(np1)

              

array([3, 4, 6, 8, 9])

In [26]:
np1=np.array([1,4,2])   #solve this issue as hometask
np2=np.array([3,1,6])
np.concatenate(np1, np2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [29]:
np1=np.array([[1,2,3],[3,4,5]])
np2=np.array([[5,6,5]])
np.concatenate((np1, np2), axis=0)    #axis divides one d and 2 d array


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 5]])

In [11]:
# shape and size of an array
np1=np.array([[[1,2,3],[2,3,4],[5,6,8],[3,7,7]]])
print(np1)
arr1=arr2.reshape(2,2)


[[[1 2 3]
  [2 3 4]
  [5 6 8]
  [3 7 7]]]


In [7]:
#how to save and load numpy objects
arr1=np.array([2,5,3,6])                            #create an array
np.save('filenew', arr1)                            #create a file and save array in this fiie
arr2=np.load('filenew.npy')
print(arr2)                                         #load the array from this file

[2 5 3 6]


In [3]:
import pandas as pd
import numpy as np


In [7]:
arr1=np.array([[1,4,3],[5,3,5],[5,3,6],[6,3,2],[5,3,6],[6,3,6]])
df=pd.DataFrame(arr1)
df.to_csv('pd.csv')          # COMMA-SEPARATED VALUES
data=pd.read_csv('pd.csv')
print(df)

   0  1  2
0  1  4  3
1  5  3  5
2  5  3  6
3  6  3  2
4  5  3  6
5  6  3  6


In [ ]:
pd_df=pd_arr.to_csv

In [5]:
import numpy as np
arr1=np.array([[[2,4,3],[3,6,4]],[[1,6,4],[9,5,4]],[[7,4,2],[2,1,4]]])
print(arr1)

[[[2 4 3]
  [3 6 4]]

 [[1 6 4]
  [9 5 4]]

 [[7 4 2]
  [2 1 4]]]


In [3]:
import numpy as np
a=np.arange(9)
print(a)


[0 1 2 3 4 5 6 7 8]


In [6]:
b=a.reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
arr=np.array([[2,4,5,6,7,8,9],[5,3,2,5,3,7,9]])
arr.shape

(2, 7)

In [2]:
import numpy as np

In [3]:
arr1=np.array([2,4,6])   # CONCATENATION OF TWO ARRAYS
arr2=np.array([1,2,3])
np.concatenate((arr1,arr2))

array([2, 4, 6, 1, 2, 3])

In [ ]:
3.1## print first  file rows of dataset
 3.2 # print first n rows of dataset
    # print last n rows of dataset
3.3 # describe your dataset
3.5# find number of columns in every row with null values
3.6# print no of rows and columns type of data and number of missing value  
use  .info() and .describe()